### ISSUE TITLE
sticky footer flex alternative

### ISSUE THREAD

**Issue by cmnstmntmn** [francoisromain/system.css-boilerplate#1]
there's a nicer way to make this [**sticky-footer**](https://github.com/francoisromain/system.css-boilerplate/blob/gh-pages/src/sticky-footer.css) act the same, without using position absolute, margin on body and height on footer.

here's how https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

```css
/**
 * 1. Avoid the IE 10-11 `min-height` bug.
 * 2. Set `flex-shrink` to `0` to prevent some browsers from
 *    letting these items shrink to smaller than their content's default
 *    minimum size. See http://bit.ly/1Mn35US for details.
 * 3. Use `%` instead of `vh` since `vh` is buggy in older mobile Safari.
 */

.Site {
  display: flex;
  flex-direction: column;
  height: 100%; /* 1, 3 */
}

.Site-header,
.Site-footer {
  flex: none; /* 2 */
}

.Site-content {
  flex: 1 0 auto; /* 2 */
}
```

i could make a PR
