### ISSUE TITLE
.row:after cause odd behaviour

### ISSUE THREAD

**Issue by cmnstmntmn** [francoisromain/system.css-boilerplate#3]
```css
.u-flexJustifyBetween {
    justify-content: space-between!important;
}
```

<img width="547" alt="screen shot 2016-07-04 at 12 19 11" src="https://cloud.githubusercontent.com/assets/2312755/16556258/a0cc7314-41e1-11e6-8315-c9897f028670.png">

and this is how it looks

<img width="1049" alt="screen shot 2016-07-04 at 12 34 46" src="https://cloud.githubusercontent.com/assets/2312755/16556625/c148a8e0-41e3-11e6-9cb2-9e21175cee17.png">

the `:after` element is the yellow dot

**Comment by francoisromain** [comment]
Do you have a link online?

**Comment by cmnstmntmn** [comment]
the expected behaviour: https://jsfiddle.net/jhhegj80/1/

and the behaviour now: https://jsfiddle.net/jhhegj80/

**Comment by cmnstmntmn** [comment]
```css
.row {
  gs: row;
}
```

should generate this insted

https://github.com/suitcss/components-grid/blob/master/lib/grid.css#L24-L30
